# Generated by Django 4.1 on 2022-11-28 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=98)),
                ("data", models.CharField(max_length=25)),
                ("natureza", models.CharField(max_length=98)),
                ("sinal", models.CharField(max_length=1)),
                ("valor", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.CharField(max_length=25)),
                ("dono_nome", models.CharField(max_length=14)),
                ("nome_loja", models.CharField(max_length=19)),
            ],
        ),
    ]
