# Generated by Django 4.1 on 2022-11-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
    ]
